# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch 

# Create random tensor
torch.randn(size = (7,7))

tensor([[-0.4397, -0.4567,  1.0364, -1.0498,  0.4284, -1.9930, -0.5437],
        [-0.4245, -0.7758, -0.7391,  0.3040,  0.1722, -0.1145,  0.9596],
        [ 1.5569, -1.1246, -0.0297, -0.4243, -0.8287, -0.5661, -0.5134],
        [-0.0537, -1.8061,  1.2043, -1.9492,  0.5006, -0.0431, -0.5822],
        [-0.9688, -0.7347, -0.8024, -0.5846, -1.2740,  2.3145, -2.0657],
        [-0.0719, -0.2247, -0.2086,  0.8171, -0.5119,  1.2889,  0.0041],
        [ 0.3425, -0.3234,  0.2051, -0.5473, -0.5531, -1.0279, -0.1516]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
t1 = torch.randn(size = (1,7))
t2 = torch.randn(size = (1,7))

# Perform matrix multiplication 
t1 @ t2.T

tensor([[-0.8655]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
MANUAL_SEED = 42
torch.manual_seed(MANUAL_SEED)

# Create two random tensors
t1 = torch.randn(size = (7,1))
t2 = torch.randn(size = (1,1))

# Matrix multiply tensors
t1 @ t2

tensor([[-0.2148],
        [-0.0822],
        [-0.1496],
        [-0.1470],
        [ 0.7164],
        [ 0.1189],
        [-1.4088]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

`torch.cuda.manual_seed` is available as an GPU equivalent 

In [16]:
# Set random seed on the GPU
MANUAL_SEED = 1234
torch.cuda.manual_seed(MANUAL_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
MANUAL_SEED = 1234

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
t1 = torch.randn(size=(2,3)).to(device=device)
t2 = torch.randn(size=(2,3)).to(device=device)

print(t1,t2)

tensor([[ 0.4617,  0.2674,  0.5349],
        [ 0.8094,  1.1103, -1.6898]], device='cuda:0') tensor([[-0.9890,  0.9580,  1.3221],
        [ 0.8172, -0.7658, -0.7506]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
output = t1 @ t2.T
output

tensor([[ 0.5068, -0.2290],
        [-1.9709,  1.0795]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(output.min())
# Find min
print(output.max())

tensor(-1.9709, device='cuda:0')
tensor(1.0795, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
print(output.argmax().item())

# Find arg min
print(output.argmin().item())

3
2



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [7]:
# Set seed
import torch
MANUAL_SEED = 7

# Create random tensor
random_tensor = torch.randn(size=(1,1,1,10))

# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor,random_tensor.shape)
print(random_tensor_squeezed, random_tensor_squeezed.shape)

tensor([[[[-0.9151, -0.0166, -0.5843,  0.3944, -0.1776,  1.5913, -0.3650,
           -1.1434,  1.2808, -0.5352]]]]) torch.Size([1, 1, 1, 10])
tensor([-0.9151, -0.0166, -0.5843,  0.3944, -0.1776,  1.5913, -0.3650, -1.1434,
         1.2808, -0.5352]) torch.Size([10])
