# 00. PyTorch Fundamentals

**Fundementals**

In [2]:
import torch 
torch.__version__

'2.0.0+cu118'

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [3]:
scalar = torch.tensor(7)
print(scalar)
print("dimension " , scalar.ndim)
print("Retrive the number from scalar  ", scalar.item())

tensor(7)
dimension  0
retive the number from scalar   7


A vector is a single dimension tensor but can contain many numbers. 


`shape` attribute tells you how the elements inside them are arranged.

In [4]:
vector = torch.tensor([4,5,9])
print(vector)
print("dimension ", vector.ndim)
print("Shape ", vector.shape)

tensor([4, 5, 9])
dimension  1
Shape  torch.Size([3])


In [5]:
matrix = torch.tensor([[7,8],
                      [9,10]])
print(matrix)
print("dimension" , matrix.ndim)
print("size", matrix.size())

tensor([[ 7,  8],
        [ 9, 10]])
dimension 2
size torch.Size([2, 2])


In [6]:
tensor = torch.tensor([[[1,3,4],
                       [2,4,7],
                       [7,8,0]]])
print(tensor)
print("dimension ",tensor.ndim)
print("size ",tensor.size())

tensor([[[1, 3, 4],
         [2, 4, 7],
         [7, 8, 0]]])
dimension  3
size  torch.Size([1, 3, 3])


**Random Tensors**

In [7]:
random_tensor = torch.rand(size = (2,3))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.dtype)

tensor([[0.5120, 0.8640, 0.7473],
        [0.4981, 0.2302, 0.2306]])
2
torch.Size([2, 3])
torch.float32


In [8]:
img_size_tensor = torch.rand(size = (2,244,244))
print(img_size_tensor.size())
print(img_size_tensor.ndim)
print(img_size_tensor)

torch.Size([2, 244, 244])
3
tensor([[[0.3402, 0.8385, 0.6069,  ..., 0.9604, 0.5758, 0.9679],
         [0.1572, 0.5449, 0.2226,  ..., 0.5071, 0.2701, 0.7006],
         [0.0659, 0.4626, 0.7292,  ..., 0.6822, 0.2781, 0.0768],
         ...,
         [0.4151, 0.8583, 0.9644,  ..., 0.8093, 0.9541, 0.0216],
         [0.9331, 0.6560, 0.4613,  ..., 0.5005, 0.6078, 0.0818],
         [0.6228, 0.2503, 0.2066,  ..., 0.9106, 0.3193, 0.5696]],

        [[0.7317, 0.4505, 0.7840,  ..., 0.0538, 0.2118, 0.4713],
         [0.2162, 0.2610, 0.5978,  ..., 0.3763, 0.2403, 0.4977],
         [0.7271, 0.2232, 0.1710,  ..., 0.0909, 0.2769, 0.8965],
         ...,
         [0.3620, 0.0589, 0.9780,  ..., 0.7204, 0.8454, 0.1442],
         [0.6608, 0.3466, 0.1239,  ..., 0.6287, 0.3220, 0.4940],
         [0.2434, 0.4434, 0.7015,  ..., 0.6454, 0.6945, 0.0096]]])


**Zeros and ones**

In [9]:
zeros = torch.zeros(size = (3,3))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size = (3,3))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [10]:
zero_ten = torch.arange(0,100,10)
zero_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Sometimes if you wanna make tensors of same size we can use `torch.ones_like(input)` and `torch.zero_like(input)`

In [11]:
print(torch.ones_like(zero_ten))
print(torch.zeros_like(zero_ten))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


**Tensor datatypes**

In [12]:
float_tensor = torch.tensor([1.0,2.0,3,4,5],
                            device = None,
                            requires_grad = False,
                            dtype = None)

float_tensor , float_tensor.dtype, float_tensor.size(), float_tensor.device

(tensor([1., 2., 3., 4., 5.]),
 torch.float32,
 torch.Size([5]),
 device(type='cpu'))

In [13]:
float16_tensor = torch.tensor([1.0,9.0,9.0],
                              dtype = torch.float16)
float16_tensor

tensor([1., 9., 9.], dtype=torch.float16)

**Tensor manipulation**

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

Note - values inside a `tensor` does not change unless reassigned 


In [14]:
tensor = torch.tensor([1,2,4,5])
print(tensor * 10, tensor - 10, tensor * 12)
print(tensor.mul(12),tensor.add(12),tensor.sub(10))

tensor([10, 20, 40, 50]) tensor([-9, -8, -6, -5]) tensor([12, 24, 48, 60])
tensor([12, 24, 48, 60]) tensor([13, 14, 16, 17]) tensor([-9, -8, -6, -5])


**Matrix Multiplication**

- The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

- The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [15]:
# vector x vector 
tensor_1 = torch.randn(3)
tensor_2 = torch.randn(3)
print(torch.matmul(tensor_1,tensor_2).size())

# vector x matrix 
tensor_1 = torch.randn(3)
tensor_2 = torch.randn(3,2)
print((tensor_1 @ tensor_2).size())

# batched matrix x broadcasted vector 
tensor_1 = torch.randn(10,3,4)
tensor_2 = torch.randn(4)
print((tensor_1 @ tensor_2).size())

# batched matrix x batched matirx
tensor_1 = torch.randn(10 , 3, 4)
tensor_2 = torch.randn(10, 4 , 5)
print((tensor_1 @ tensor_2).size())

# batched matrix x broadcasted matrix
tensor_1 = torch.randn(10 , 3, 4)
tensor_2 = torch.randn(4,5)
print((tensor_1 @ tensor_2).size())


torch.Size([])
torch.Size([2])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [16]:
A = torch.tensor([[2.,3],
                  [3,4],
                  [5,6]])

B = torch.tensor([[7.,8],
                  [9,0],
                  [2,3]])

torch.mm(A,B.T)

tensor([[38., 18., 13.],
        [53., 27., 18.],
        [83., 45., 28.]])

**torch.nn.Linear()**

In [19]:
torch.manual_seed(23)

linear = torch.nn.Linear(in_features=2,
                         out_features =6)

print("Input shape is ", A.shape)
print("Output shape is ",linear(A).shape)

Input shape is  torch.Size([3, 2])
Output shape is  torch.Size([3, 6])


**Finding the min, max, mean, sum, etc (aggregation)**

In [20]:
x = torch.arange(0,100,10)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [21]:
tensor = torch.arange(10,100,10)
print("Max at :", tensor.argmax())
print("Min at :",tensor.argmin())

Max at : tensor(8)
Min at : tensor(0)


**Change tensor datatype**

In [22]:
tensor = torch.arange(10,100,10)
print(tensor.dtype)

tensor.type(torch.float32)

torch.int64


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

**Reshaping, stacking, squeezing and unsqueezing**

* `torch.reshape(input, shape)` --- Reshapes a tensor according to the shape specified 

* `torch.Tensor.view(shape)` --- Reshape and present the view of tensor , it shares data with the original tensor so any change in the view changes original tensor 

* `torch.Tensor.stack([x,x,x],dim=0)`--- Stacking tensor on top of other , dim=0 means through row-wise

* `torch.Tensor.squeeze()` -- remove one dim

* ` torch.Tensor.permute(2,0,1)` -- shifts axis by 0->2 , 1->0 , 2->1 of original tensor

In [23]:
tensor = torch.tensor([1,2,3,4,5,6])
print(tensor.shape)

# adding extra dim 
print(tensor.reshape(1,6))

#change view 
print(tensor.view(2,3))

# stack new tensor on top of other
stacked = torch.stack([tensor,tensor,tensor], dim=0)
print(stacked)

# removing a dim from tensor
tensor_reshaped = tensor.reshape(1,6)
print("Before squeezing: ",tensor_reshaped.shape)
print("After squeezing :",tensor_reshaped.squeeze().shape)


torch.Size([6])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])
Before squeezing:  torch.Size([1, 6])
After squeezing : torch.Size([6])


In [24]:
# permute tensor 
original = torch.randn(size = (224,224,3))
permute = original.permute(2,0,1) # shifts axis by 0->2 , 1->0 , 2->1
print("Original shape", original.shape)
print("permute",permute.shape)

Original shape torch.Size([224, 224, 3])
permute torch.Size([3, 224, 224])


**Indexing(slicing data from tensor)**

In [26]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [25]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x[:,:,1])
print(x[:,1,1])

tensor([[2, 5, 8]])
tensor([5])


**PyTorch tensors & NumPy**

In [27]:
import torch
import numpy
tensor = numpy.array([1,2,4,5,5,7])
trail = torch.from_numpy(tensor)
array = trail.numpy()
print(trail,array)

tensor([1, 2, 4, 5, 5, 7], dtype=torch.int32) [1 2 4 5 5 7]


In [28]:
#  if you change the original tensor, the new numpy_tensor stays the same.
trail+1,array

(tensor([2, 3, 5, 6, 6, 8], dtype=torch.int32), array([1, 2, 4, 5, 5, 7]))

**reproducibility**

In [29]:
import torch
import random 

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
print(random_tensor)

random_tensor_2 = torch .rand(3,2)
print(random_tensor_2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])


In [30]:
torch.cuda.is_available(),random_tensor_2.to('cuda'),random_tensor_2.cpu()

(True,
 tensor([[0.8694, 0.5677],
         [0.7411, 0.4294],
         [0.8854, 0.5739]], device='cuda:0'),
 tensor([[0.8694, 0.5677],
         [0.7411, 0.4294],
         [0.8854, 0.5739]]))