# 00. PyTorch Fundamentals

**Fundementals**

In [1]:
import torch 
torch.__version__

'2.0.0+cu118'

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [10]:
scalar = torch.tensor(7)
print(scalar)
print("dimension " , scalar.ndim)
print("retive the number from scalar  ", scalar.item())

tensor(7)
dimension  0
retive the number from scalar   7


A vector is a single dimension tensor but can contain many numbers. `shape` attribute. The shape tells you how the elements inside them are arranged.

In [11]:
vector = torch.tensor([4,5,9])
print(vector)
print("dimension ", vector.ndim)
print("Shape ", vector.shape)

tensor([4, 5, 9])
dimension  1
Shape  torch.Size([3])


In [15]:
matrix = torch.tensor([[7,8],
                      [9,10]])
print(matrix)
print("dimension" , matrix.ndim)
print("size", matrix.size())

tensor([[ 7,  8],
        [ 9, 10]])
dimension 2
size torch.Size([2, 2])


In [20]:
tensor = torch.tensor([[[1,3,4],
                       [2,4,7],
                       [7,8,0]]])
print(tensor)
print("dimension ",tensor.ndim)
print("size ",tensor.size())

tensor([[[1, 3, 4],
         [2, 4, 7],
         [7, 8, 0]]])
dimension  3
size  torch.Size([1, 3, 3])


**Random Tensors**

In [26]:
random_tensor = torch.rand(size = (2,3))
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.dtype)

tensor([[0.4658, 0.4792, 0.5222],
        [0.6932, 0.6971, 0.0952]])
torch.Size([2, 3])
torch.float32


In [29]:
img_size_tensor = torch.rand(size = (2,244,244))
print(img_size_tensor.size())
print(img_size_tensor.ndim)
print(img_size_tensor)

torch.Size([2, 244, 244])
3
tensor([[[0.2247, 0.9811, 0.0762,  ..., 0.5815, 0.5022, 0.4958],
         [0.2857, 0.3874, 0.2000,  ..., 0.8606, 0.9209, 0.9001],
         [0.4643, 0.5475, 0.7571,  ..., 0.1034, 0.4445, 0.4029],
         ...,
         [0.3474, 0.1396, 0.0200,  ..., 0.8883, 0.9143, 0.8574],
         [0.9854, 0.3489, 0.3584,  ..., 0.0707, 0.7905, 0.8257],
         [0.6509, 0.4158, 0.3301,  ..., 0.7809, 0.5983, 0.4078]],

        [[0.2825, 0.5481, 0.7359,  ..., 0.3509, 0.8013, 0.8422],
         [0.3744, 0.5729, 0.7589,  ..., 0.4837, 0.7782, 0.1565],
         [0.7088, 0.1329, 0.7155,  ..., 0.5739, 0.6590, 0.1316],
         ...,
         [0.2500, 0.5528, 0.9486,  ..., 0.0567, 0.8205, 0.3442],
         [0.6624, 0.6283, 0.6720,  ..., 0.9325, 0.9828, 0.3318],
         [0.7375, 0.7155, 0.2183,  ..., 0.6637, 0.6597, 0.4871]]])


**Zeros and ones**

In [2]:
zeros = torch.zeros(size = (3,3))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size = (3,3))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [4]:
zero_ten = torch.arange(0,100,10)
zero_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Sometimes if you wanna make tensors of same size we can use `torch.ones_like(input)` and `torch.zero_like(input)`

In [8]:
print(torch.ones_like(zero_ten))
print(torch.zeros_like(zero_ten))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


**Tensor datatypes**

In [16]:
float_tensor = torch.tensor([1.0,2.0,3,4,5],
                            device = None,
                            requires_grad = False,
                            dtype = None)

float_tensor , float_tensor.dtype, float_tensor.size(), float_tensor.device

(tensor([1., 2., 3., 4., 5.]),
 torch.float32,
 torch.Size([5]),
 device(type='cpu'))

In [17]:
float16_tensor = torch.tensor([1.0,9.0,9.0],
                              dtype = torch.float16)
float16_tensor

tensor([1., 9., 9.], dtype=torch.float16)

**Tensor manipulation**

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

Note - values inside a `tensor` does not change unless reassigned 


In [24]:
tensor = torch.tensor([1,2,4,5])
print(tensor * 10, tensor - 10, tensor * 12)
print(tensor.mul(12),tensor.add(12),tensor.sub(10))

tensor([10, 20, 40, 50]) tensor([-9, -8, -6, -5]) tensor([12, 24, 48, 60])
tensor([12, 24, 48, 60]) tensor([13, 14, 16, 17]) tensor([-9, -8, -6, -5])


**Matrix Multiplication**

- The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

- The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [12]:
# vector x vector 
tensor_1 = torch.randn(3)
tensor_2 = torch.randn(3)
print(torch.matmul(tensor_1,tensor_2).size())

# vector x matrix 
tensor_1 = torch.randn(3)
tensor_2 = torch.randn(3,2)
print((tensor_1 @ tensor_2).size())

# batched matrix x broadcasted vector 
tensor_1 = torch.randn(10,3,4)
tensor_2 = torch.randn(4)
print((tensor_1 @ tensor_2).size())

# batched matrix x batched matirx
tensor_1 = torch.randn(10 , 3, 4)
tensor_2 = torch.randn(10, 4 , 5)
print((tensor_1 @ tensor_2).size())

# batched matrix x broadcasted matrix
tensor_1 = torch.randn(10 , 3, 4)
tensor_2 = torch.randn(4,5)
print((tensor_1 @ tensor_2).size())


torch.Size([])
torch.Size([2])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [21]:
A = torch.tensor([[2.,3],
                  [3,4],
                  [5,6]])

B = torch.tensor([[7.,8],
                  [9,0],
                  [2,3]])

torch.mm(A,B.T)

tensor([[38., 18., 13.],
        [53., 27., 18.],
        [83., 45., 28.]])

**torch.nn.Linear()**

In [23]:
torch.manual_seed(23)

linear = torch.nn.Linear(in_features=2,
                         out_features = 6)

print("Output shape is ",linear(A))
print("Shape is ", linear(A).size())

Output shape is  tensor([[-0.6919, -0.7496, -0.4094,  0.8194, -1.7164, -1.4301],
        [-1.0920, -1.0615, -0.3137,  1.1218, -2.1159, -1.7474],
        [-1.8921, -1.6852, -0.1224,  1.7268, -2.9149, -2.3821]],
       grad_fn=<AddmmBackward0>)
Shape is  torch.Size([3, 6])


**Finding the min, max, mean, sum, etc (aggregation)**

In [6]:
x = torch.arange(0,100,10)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [7]:
tensor = torch.arange(10,100,10)
print("Max at :", tensor.argmax())
print("Min at :",tensor.argmin())

Max at : tensor(8)
Min at : tensor(0)


**Change tensor datatype**

In [12]:
tensor = torch.arange(10,100,10)
print(tensor.dtype)

tensor.type(torch.float32)

torch.int64


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

**Reshaping, stacking, squeezing and unsqueezing**

* `torch.reshape(input, shape)` --- Reshapes a tensor according to the shape specified 

* `torch.Tensor.view(shape)` --- Reshape and present the view of tensor , it shares data with the original tensor so any change in the view changes og tensor 

* `torch.Tensor.stack([x,x,x],dim=0)`--- Stacking tensor on top of other , dim=0 means through row-wise

* `torch.Tensor.squeeze()` -- remove one dim

* ` torch.Tensor.permute(2,0,1)` -- shifts axis by 0->2 , 1->0 , 2->1 of og tensor

In [13]:
tensor = torch.tensor([1,2,3,4,5,6])
print(tensor.shape)

# adding extra dim 
print(tensor.reshape(1,6))

#change view 
print(tensor.view(2,3))

# stack new tensor on top of other
stacked = torch.stack([tensor,tensor,tensor], dim=0)
print(stacked)

# removing a dim from tensor
tensor_reshaped = tensor.reshape(1,6)
print("Before squeezing: ",tensor_reshaped.shape)
print("After squeezing :",tensor_reshaped.squeeze().shape)


torch.Size([6])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])
Before squeezing:  torch.Size([1, 6])
After squeezing : torch.Size([6])


In [14]:
# permute tensor 
original = torch.randn(size = (224,224,3))
permute = original.permute(2,0,1) # shifts axis by 0->2 , 1->0 , 2->1
print("Original shape", original.shape)
print("permute",permute.shape)

Original shape torch.Size([224, 224, 3])
permute torch.Size([3, 224, 224])


**Indexing(slicing data from tensor)**

In [1]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x[:,:,1])
print(x[:,1,1])

tensor([[2, 5, 8]])
tensor([5])


**PyTorch tensors & NumPy**

In [2]:
import torch
import numpy
tensor = numpy.array([1,2,4,5,5,7])
trail = torch.from_numpy(tensor)
array = trail.numpy()
print(trail,array)

tensor([1, 2, 4, 5, 5, 7], dtype=torch.int32) [1 2 4 5 5 7]


In [3]:
#  if you change the original tensor, the new numpy_tensor stays the same.
trail+1,array

(tensor([2, 3, 5, 6, 6, 8], dtype=torch.int32), array([1, 2, 4, 5, 5, 7]))

**reproducibility**

In [1]:
import torch
import random 

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
print(random_tensor)

random_tensor_2 = torch .rand(3,2)
print(random_tensor_2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])


In [2]:
torch.cuda.is_available(),random_tensor_2.to('cuda'),random_tensor_2.cpu()

(True,
 tensor([[0.8694, 0.5677],
         [0.7411, 0.4294],
         [0.8854, 0.5739]], device='cuda:0'),
 tensor([[0.8694, 0.5677],
         [0.7411, 0.4294],
         [0.8854, 0.5739]]))

# 00. PyTorch Fundamentals Exercises

In [3]:
# run CUDA operations.

cuda = torch.device('cuda')
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1') # Indexing the GPUs

In [4]:
x = torch.tensor([1.,2.], device=cuda)# device = cuda0 gives error
y = torch.tensor([1.,9.], device=cuda)# only one GPU is available   

x + y


tensor([ 2., 11.], device='cuda:0')

In [16]:
# 2. Create a random tensor with shape (7, 7).
torch.manual_seed(0)
randon = torch.rand(7,7)
print(randon)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


In [28]:
# 3. Perform a matrix multiplication on the tensor another random tensor with shape (1, 7)
torch.manual_seed(0)
matrix = torch.randn(1,7)
print((matrix.T) * randon)
print(matrix.shape)
print(randon.shape)
# Set the random seed to 0 and do 2 & 3 over again.

# Set random seed on the GPU
torch.cuda.manual_seed(21)
torch.randn(2,4, device=cuda)

tensor([[ 0.7647,  1.1838,  0.1363,  0.2035,  0.4737,  0.9771,  0.7552],
        [-0.2630, -0.1337, -0.1855, -0.1024, -0.1179, -0.0066, -0.0495],
        [-0.6403, -1.1297, -1.5201, -1.7431, -0.3508, -0.6150, -1.4851],
        [ 0.5202,  0.2257,  0.4969,  0.2384,  0.3143,  0.5416,  0.0206],
        [-0.2009, -0.4050, -0.3309, -1.0108, -0.1908, -0.2926, -0.1634],
        [-0.0444, -0.2911, -1.3004, -1.0113, -1.0382, -0.7361, -0.3408],
        [ 0.2358,  0.0134,  0.0560,  0.0977,  0.3289,  0.3199,  0.1122]])
torch.Size([1, 7])
torch.Size([7, 7])


tensor([[ 0.7362,  0.2507,  0.4451, -0.5870],
        [ 1.1781, -1.2679, -0.2980,  0.0177]], device='cuda:0')

In [40]:
print(torch.cuda.is_available())
A = torch.randn(2,3, device=cuda)
B = torch.randn(2,3, device = cuda)
print(A,B)
# Perform a matrix multiplication on the tensors
out = A * B
print(out, torch.argmax(out),torch.argmin(out))

True
tensor([[ 0.2748,  1.2245,  0.3228],
        [-0.1728, -0.7619, -1.5839]], device='cuda:0') tensor([[ 2.2144, -0.3119, -0.4010],
        [-0.4349,  1.1050,  1.7011]], device='cuda:0')
tensor([[ 0.6086, -0.3819, -0.1294],
        [ 0.0752, -0.8419, -2.6943]], device='cuda:0') tensor(0, device='cuda:0') tensor(5, device='cuda:0')


In [41]:
random_tensor_10 = torch.rand(size = (1,1,1,10))
print(random_tensor_10.shape)
random_tensor_10 = random_tensor_10.squeeze(dim=0)
random_tensor_10.shape

torch.Size([1, 1, 1, 10])


torch.Size([1, 1, 10])