# 00. PyTorch Fundamentals

**Fundementals**

In [2]:
import torch 
torch.__version__

'2.2.2+cu118'

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [3]:
scalar = torch.tensor(7)
print(scalar)
print("dimension :" , scalar.ndim)
print("Retrive the number from scalar :", scalar.item())

tensor(7)
dimension : 0
Retrive the number from scalar : 7


A vector is a single dimension tensor but can contain many numbers. 


`shape` attribute tells you how the elements inside them are arranged.

In [4]:
vector = torch.tensor([4,5,9])
print(vector)
print("dimension ", vector.ndim)
print("Shape ", vector.shape)

tensor([4, 5, 9])
dimension  1
Shape  torch.Size([3])


In [5]:
matrix = torch.tensor([[7,8,2],
                      [9,10,1]])
print(matrix)
print("dimension" , matrix.ndim)
print("size", matrix.size())

tensor([[ 7,  8,  2],
        [ 9, 10,  1]])
dimension 2
size torch.Size([2, 3])


In [6]:
tensor = torch.tensor([[[1,3,4,2],
                       [2,4,7,7],
                       [7,8,0,8]]])
print(tensor)
print("dimension ",tensor.ndim)
print("size ",tensor.size())
print("Shape :", tensor.shape)

tensor([[[1, 3, 4, 2],
         [2, 4, 7, 7],
         [7, 8, 0, 8]]])
dimension  3
size  torch.Size([1, 3, 4])
Shape : torch.Size([1, 3, 4])


**Random Tensors**

In [7]:
random_tensor = torch.rand(size = (2,3))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.dtype)

tensor([[0.9949, 0.5947, 0.8633],
        [0.2334, 0.5073, 0.0911]])
2
torch.Size([2, 3])
torch.float32


In [8]:
img_size_tensor = torch.rand(size = (2,244,244))
print(img_size_tensor.size())
print(img_size_tensor.ndim)
print(img_size_tensor)

torch.Size([2, 244, 244])
3
tensor([[[0.9923, 0.0284, 0.7741,  ..., 0.5308, 0.4931, 0.1102],
         [0.7288, 0.7150, 0.3817,  ..., 0.1734, 0.6838, 0.9756],
         [0.0993, 0.1578, 0.3621,  ..., 0.1792, 0.2037, 0.5455],
         ...,
         [0.0693, 0.2197, 0.7196,  ..., 0.3659, 0.2210, 0.1279],
         [0.1135, 0.8122, 0.1289,  ..., 0.6931, 0.4363, 0.6813],
         [0.5917, 0.3113, 0.6324,  ..., 0.0636, 0.7593, 0.4564]],

        [[0.9025, 0.5228, 0.6632,  ..., 0.8856, 0.5358, 0.2924],
         [0.8682, 0.3306, 0.7210,  ..., 0.9193, 0.9999, 0.9189],
         [0.6737, 0.4108, 0.4303,  ..., 0.0079, 0.1809, 0.8828],
         ...,
         [0.8661, 0.7211, 0.3942,  ..., 0.6375, 0.2718, 0.7434],
         [0.0727, 0.5140, 0.7861,  ..., 0.2115, 0.3715, 0.3334],
         [0.4309, 0.8163, 0.1474,  ..., 0.5590, 0.2078, 0.9695]]])


**Zeros and ones**

In [9]:
zeros = torch.zeros(size = (3,3))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size = (3,3))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [10]:
zero_ten = torch.arange(0,100,10)
zero_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Sometimes if you wanna make tensors of same size we can use `torch.ones_like(input)` and `torch.zero_like(input)`

In [11]:
print(torch.ones_like(zero_ten))
print(torch.zeros_like(zero_ten))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


**Tensor datatypes**

In [12]:
float_tensor = torch.tensor([1.0,2.0,3,4,5],
                            device = None,
                            requires_grad = False,
                            dtype = None)

float_tensor2 = torch.tensor([1.,2,3.,4,5.],
                            device='cuda',
                            requires_grad=True,
                            dtype=None)

print(float_tensor2,float_tensor2.dtype,float_tensor2.device)
float_tensor , float_tensor.dtype, float_tensor.size(), float_tensor.device

tensor([1., 2., 3., 4., 5.], device='cuda:0', requires_grad=True) torch.float32 cuda:0


(tensor([1., 2., 3., 4., 5.]),
 torch.float32,
 torch.Size([5]),
 device(type='cpu'))

In [13]:
float64_tensor = torch.tensor([1.0,9.0,9.0],
                              dtype = torch.float64)
float64_tensor

tensor([1., 9., 9.], dtype=torch.float64)

**Tensor manipulation**

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

Note - values inside a `tensor` does not change unless reassigned 


In [14]:
tensor = torch.tensor([1,2,4,5])

print(tensor + 10, tensor - 10, tensor * 12, tensor/2)
print(tensor.mul(12),tensor.add(12),tensor.sub(10), tensor.divide(4))

tensor([11, 12, 14, 15]) tensor([-9, -8, -6, -5]) tensor([12, 24, 48, 60]) tensor([0.5000, 1.0000, 2.0000, 2.5000])
tensor([12, 24, 48, 60]) tensor([13, 14, 16, 17]) tensor([-9, -8, -6, -5]) tensor([0.2500, 0.5000, 1.0000, 1.2500])


**Matrix Multiplication**

- The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

- The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [15]:
# vector x vector 
tensor_1 = torch.randn(3)
tensor_2 = torch.randn(3)
print(torch.matmul(tensor_1,tensor_2).size())

# vector x matrix 
tensor_1 = torch.randn(3)
tensor_2 = torch.randn(3,2)
print((tensor_1 @ tensor_2).size())

# batched matrix x broadcasted vector 
tensor_1 = torch.randn(10,3,4)
tensor_2 = torch.randn(4)
print((tensor_1 @ tensor_2).size())

# batched matrix x batched matirx
tensor_1 = torch.randn(10 , 3, 4)
tensor_2 = torch.randn(10, 4 , 5)
print((tensor_1 @ tensor_2).size())

# batched matrix x broadcasted matrix
tensor_1 = torch.randn(10 , 3, 4)
tensor_2 = torch.randn(4,5)
print((tensor_1 @ tensor_2).size())

torch.Size([])
torch.Size([2])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [16]:
A = torch.tensor([[2.,3],
                  [3,4],
                  [5,6]])

B = torch.tensor([[7.,8],
                  [9,0],
                  [2,3]])

torch.mm(A,B.T)

tensor([[38., 18., 13.],
        [53., 27., 18.],
        [83., 45., 28.]])

**torch.nn.Linear()**

In [17]:
torch.manual_seed(23)

linear = torch.nn.Linear(in_features=2,
                         out_features =6)

print("Input shape is ", A.shape)
print("Output shape is ",linear(A).shape)

Input shape is  torch.Size([3, 2])
Output shape is  torch.Size([3, 6])


**Finding the min, max, mean, sum, etc (aggregation)**

In [18]:
x = torch.arange(0,100,10)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [19]:
tensor = torch.arange(10,100,10)
print("Max at :", tensor.argmax())
print("Min at :",tensor.argmin())

Max at : tensor(8)
Min at : tensor(0)


**Change tensor datatype**

In [20]:
tensor = torch.arange(10,100,10)
print(tensor.dtype)

tensor.type(torch.float32)

torch.int64


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

**Reshaping, stacking, squeezing and unsqueezing**

* `torch.reshape(input, shape)` --- Reshapes a tensor according to the shape specified 

* `torch.Tensor.view(shape)` --- Reshape and present the view of tensor , it shares data with the original tensor so any change in the view changes original tensor 

* `torch.Tensor.stack([x,x,x],dim=0)`--- Stacking tensor on top of other , dim=0 means through row-wise

* `torch.Tensor.squeeze()` -- remove one dim

* ` torch.Tensor.permute(2,0,1)` -- shifts axis by 0->2 , 1->0 , 2->1 of original tensor

In [21]:
tensor = torch.tensor([1,2,3,4,5,6])
print(tensor.shape)

# adding extra dim 
print(tensor.reshape(1,6))

#change view 
print(tensor.view(2,3)) #shares the data with org tensor

# stack new tensor on top of other
stacked = torch.stack([tensor,tensor,tensor], dim=0)
print(stacked)

# removing a dim from tensor
tensor_reshaped = tensor.reshape(1,6)
print("Before squeezing: ",tensor_reshaped.shape)
print("After squeezing :",tensor_reshaped.squeeze().shape)

torch.Size([6])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])
Before squeezing:  torch.Size([1, 6])
After squeezing : torch.Size([6])


In [22]:
# permute tensor 
original = torch.randn(size = (224,224,3))
permute = original.permute(2,0,1) # shifts axis by 0->2 , 1->0 , 2->1
print("Original shape", original.shape)
print("permute",permute.shape)

Original shape torch.Size([224, 224, 3])
permute torch.Size([3, 224, 224])


**Indexing(slicing data from tensor)**

In [23]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x)
print(x[:,:,1])
print(x[:,1,1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[2, 5, 8]])
tensor([5])


**PyTorch tensors & NumPy**

In [24]:
import torch
import numpy
tensor = numpy.array([1,2,4,5,5,7])
trail = torch.from_numpy(tensor)
array = trail.numpy()
print(trail,array)

tensor([1, 2, 4, 5, 5, 7], dtype=torch.int32) [1 2 4 5 5 7]


In [25]:
#  if you change the original tensor, the new numpy_tensor stays the same.
trail+1,array

(tensor([2, 3, 5, 6, 6, 8], dtype=torch.int32), array([1, 2, 4, 5, 5, 7]))

**reproducibility**

In [26]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
print(random_tensor)

random_tensor_2 = torch.rand(3,2)
print(random_tensor_2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])


In [27]:
torch.cuda.is_available(),random_tensor_2.to('cuda'),random_tensor_2.cpu()

(True,
 tensor([[0.8694, 0.5677],
         [0.7411, 0.4294],
         [0.8854, 0.5739]], device='cuda:0'),
 tensor([[0.8694, 0.5677],
         [0.7411, 0.4294],
         [0.8854, 0.5739]]))

Practice 

- Create a 3x3 tensor filled with zeros and change the values in the middle row to 1.
- Given a 2D tensor, extract the diagonal elements into a 1D tensor.
- Reshape a 4x4 tensor into a 2x8 tensor.
- Create a random 3D tensor of shape (2, 3, 4) and swap the first and second dimensions.
- Extract all odd-indexed elements from a 1D tensor.
- Concatenate two tensors along a new dimension.
- Permute the dimensions of a tensor of shape (3, 4, 5) to (5, 3, 4).
- Create a tensor with values from 1 to 10 and then shuffle its elements randomly.
- Slice a 2D tensor to get the last column.
- Calculate the mean of each row in a given matrix.

In [40]:
x = torch.rand(size=(3,3))
print(x)
x[:,1] = 1
print(x)

tensor([[0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])
tensor([[0.3278, 1.0000, 0.3958],
        [0.9147, 1.0000, 0.2018],
        [0.2018, 1.0000, 0.6666]])


In [44]:
# diagonal elements 
one_D_diag_tensor = x.diag()
print(one_D_diag_tensor)

tensor([0.3278, 1.0000, 0.6666])


In [46]:
# reshape 4x4 tensor to 2x8 
x = torch.rand(size = (4,4))
print(x.shape)
print(x.reshape(2,8).shape)

torch.Size([4, 4])
torch.Size([2, 8])


In [48]:
# swap dim of a 3d tensor 
matrix = torch.rand(size=(2,3,4))
print(matrix.shape)
matrix = matrix.permute(0,2,1)
matrix.shape

torch.Size([2, 3, 4])


torch.Size([2, 4, 3])

In [52]:
# all odd index element from 1d tensor 
print(one_D_diag_tensor)
odd_inx = torch.arange(1,len(one_D_diag_tensor), 2)
one_D_diag_tensor[odd_inx]

tensor([0.3278, 1.0000, 0.6666])


tensor([1.])

In [58]:
# concat 2 tensor along new dim 
A = torch.rand(size = (2,2))
B = torch.rand(size = (2,2))
torch.concat((A,B)), torch.stack((A,B), dim=0)

(tensor([[0.8196, 0.9297],
         [0.4505, 0.3881],
         [0.5073, 0.4701],
         [0.6202, 0.6401]]),
 tensor([[[0.8196, 0.9297],
          [0.4505, 0.3881]],
 
         [[0.5073, 0.4701],
          [0.6202, 0.6401]]]))

In [72]:
# shuffle elements randomly 
a = torch.arange(1,11)
torch.randperm(len(a))
# or 
import numpy as np
a = torch.arange(1,11)
np.random.shuffle(a.numpy())

In [78]:
# slice 2d tensor to get last colm
two_d = torch.rand(size=(3,4))
print(two_d)
last_colm = two_d[:,3]
print(last_colm)

tensor([[0.0134, 0.6858, 0.2255, 0.1786],
        [0.4610, 0.3335, 0.3382, 0.5161],
        [0.3939, 0.3278, 0.2606, 0.0931]])
tensor([0.1786, 0.5161, 0.0931])


In [80]:
# mena of each row 
print(two_d)
two_d.mean(dim=0)

tensor([[0.0134, 0.6858, 0.2255, 0.1786],
        [0.4610, 0.3335, 0.3382, 0.5161],
        [0.3939, 0.3278, 0.2606, 0.0931]])


tensor([0.2895, 0.4491, 0.2748, 0.2626])